apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: { name: echo, namespace: echo }
spec:
  template:
    spec:
      containers:
        - name: echo
          env:
            - name: REGION
              value: us
